Repository MINI-TEAM3/client, pull requests merged in 2023-08, with the labels that each got.

#23 ✨ Feat: 메인 헤더 내 User 재직 병원 출력
  src/components/MainHeader.tsx
Labels: 새로운 기능

#25 :sparkles: Feat: 회원가입 페이지 유효성 검사 추가
  public/junehee/sign.json
  src/lib/Validation/index.ts
  src/pages/SignUp.tsx
Labels: 새로운 기능

#26 :lipstick: Design: 버튼 컴포넌트 width, height 단위 수정
  src/components/Buttons/AnnualBtn.tsx
  src/components/Buttons/ApplyBtn.tsx
  src/components/Buttons/Btn.tsx
  src/components/Buttons/DutyBtn.tsx
  src/components/Buttons/ExelBtn.tsx
  src/components/Buttons/ModalBtn.tsx
  src/components/Buttons/RejectBtn.tsx
Labels: 문서 수정

#30 ✨ Feat: 회원가입 API 연결, 기능 구현 완료
  src/pages/SignUp.tsx
  src/styles/GlobalStyle.ts
Labels: 새로운 기능

#31 ✨ Feat: 모달 제작 및 연결
  src/App.tsx
  src/components/Buttons/AnnualBtn.tsx
  src/components/Buttons/DutyBtn.tsx
  src/components/Calendar/CalendarBody.tsx
  src/components/Modals/CalAnnualModal.tsx
  src/components/Modals/CalDutyModal.tsx
  src/components/Modals/Modal.tsx
  src/components/Modals/RequestModal.tsx
  src/hooks/useModal.ts
  src/states/stateModal.tsx
Labels: 새로운 기능

#32 📚 Docs: 마이페이지 비밀번호 재확인 UI 추가, 일부 코드 수정
  public/junehee/editPassword.json
  src/pages/MyPage.tsx
  src/pages/Password.tsx
  src/pages/UserInfo.tsx
Labels: 문서 수정

#35 ✨ Feat: API 모듈화
  src/lib/api/client.ts
  src/lib/api/index.ts
  src/lib/api/miniAPI.ts
  src/lib/types/index.ts
Labels: 새로운 기능

#36 ✨ Feat: 로그인 api 연결
  package-lock.json
  package.json
  src/components/SideBar.tsx
  src/lib/api/index.ts
  src/pages/Calendar.tsx
  src/pages/Login.tsx
  src/states/stateLogin.ts
Labels: 새로운 기능

#44 ✨ Feat: 마이페이지 API 연결 및 기능 구현 (개인정보 수정, 비밀번호 수정)
  src/lib/Validation/index.ts
  src/lib/api/index.ts
  src/pages/Password.tsx
  src/pages/UserInfo.tsx
  src/utils/decode.ts
Labels: 새로운 기능

#45 🔨 Refactor: 회원가입 API 모듈 연결, 미사용 코드 삭제
  src/pages/SignUp.tsx
Labels: 새로운 기능

#46 :bug: Fix: UserData 변경된 필드값 적용
  src/components/MainHeader.tsx
Labels: 버그

#47 ✨ Feat: 리퀘스트 모달 api 연결
  src/components/Modals/CalAnnualModal.tsx
  src/components/Modals/CalDutyModal.tsx
  src/components/Modals/Modal.tsx
  src/components/Modals/RequestModal.tsx
  src/components/Modals/checkModal.tsx
  src/lib/api/index.ts
Labels: 새로운 기능

#56 ✨ Feat: 로딩 스피너 추가, 미사용 코드 및 콘솔 로그 삭제
  index.html
  public/favicon.png
  public/logo.png
  src/components/Loading.tsx
  src/components/SideBar.tsx
  src/pages/Calendar.tsx
  src/pages/RequestList.tsx
  src/pages/UserInfo.tsx
Labels: 새로운 기능

#65 🔨 Refactor: 로그인/회원가입 Error 레이아웃 수정
  src/components/Modals/RequestModal.tsx
  src/lib/Validation/index.ts
  src/pages/Login.tsx
  src/pages/RequestList.tsx
  src/pages/SignUp.tsx
  src/utils/decode.ts
Labels: 버그

#66 🔨 Refactor: 마이페이지 프로필 이미지 수정 기능 추가, 미사용 코드 삭제
  src/components/Calendar/CalendarBody.tsx
  src/components/Modals/CalDutyModal.tsx
  src/lib/Validation/index.ts
  src/lib/types/index.ts
  src/pages/SignUp.tsx
  src/pages/UserInfo.tsx
Labels: 새로운 기능
