Repository MINI-TEAM3/client, pull requests merged in 2023-07, with the labels that each got.

#6 :sparkles: Feat: 모달용 버튼 구현
  src/components/Buttons/ModalBtn.tsx
Labels: 새로운 기능

#9 :lipstick: Design: 전역 스타일 추가
  src/styles/GlobalStyle.ts
Labels: 문서 수정

#11 :sparkles: Feat: 사이드바 레이아웃구성, MockData 임시 연결
  src/App.tsx
  src/MockData/User.ts
  src/components/SideBar.tsx
  src/styles/Themes.ts
Labels: 새로운 기능

#12 :sparkles: Feat: 라우터 수정, 글로벌 스타일 수정
  src/App.tsx
  src/components/MainHeader.tsx
  src/components/SideBar.tsx
  src/pages/Layout.tsx
  src/pages/index.tsx
  src/styles/GlobalStyle.ts
Labels: 새로운 기능

#14 :lipstick: Desgin: 메인 헤더 UI 구현 및 type 폴더 생성
  src/components/MainHeader.tsx
  src/lib/types/index.ts
Labels: 새로운 기능

#15 ✨ Feat: 엑셀 다운로드 버튼, 어드민 승인/반려 버튼 UI 구현
  src/components/Buttons/ApplyBtn.tsx
  src/components/Buttons/ExelBtn.tsx
  src/components/Buttons/RejectBtn.tsx
Labels: 새로운 기능

#18 ✨ Feat: 회원가입 페이지 UI 구현
  index.html
  package-lock.json
  package.json
  src/components/Buttons/Btn.tsx
  src/lib/Validation/index.ts
  src/pages/MyPage.tsx
  src/pages/SignUp.tsx
Labels: 버그, 문서 수정, 새로운 기능

#21 ✨ Feat: 마이페이지 UI 구현 (개인정보 수정/비밀번호 수정) 및 Recoil 설치
  package-lock.json
  package.json
  public/user.png
  src/lib/Validation/index.ts
  src/pages/MyPage.tsx
  src/pages/Password.tsx
  src/pages/UserInfo.tsx
Labels: 새로운 기능

#22 💄 Design: 개인정보 수정 페이지 UI 수정 및 더미 데이터 연결
  public/arrow.png
  public/junehee/editMypage.json
  public/junehee/mypage.json
  src/lib/types/index.ts
  src/pages/UserInfo.tsx
Labels: 문서 수정
