Repository MINI-TEAM3/client, pull requests merged in 2023-11, with the labels that each got.

#75 ✨ Feat: 전역 사용 가능한 Alert 구현 및 적용
  src/components/Alert.tsx
  src/components/Modals/CalAnnualModal.tsx
  src/components/Modals/CalDutyModal.tsx
  src/components/Modals/RequestModal.tsx
  src/components/Modals/checkModal.tsx
  src/components/SideBar.tsx
  src/lib/api/index.ts
  src/lib/types/index.ts
  src/pages/Calendar.tsx
  src/pages/Login.tsx
  src/pages/Password.tsx
  src/pages/RequestList.tsx
  src/pages/SignUp.tsx
  src/pages/UserInfo.tsx
  src/states/stateAlert.ts
  src/states/stateModal.ts
Labels: 새로운 기능

#79 ✨ Feat: 대시보드 근무 관리 데이터 연결
  src/components/DashBoard.tsx
  src/lib/api/index.ts
  src/lib/types/index.ts
  src/pages/Attendance.tsx
  src/utils/convertDay.ts
  src/utils/convertTime.ts
Labels: 새로운 기능, 완료

#81 ✨ Feat: 근무 관리 테이블 추가
  package-lock.json
  package.json
  src/components/Table/GridTable.tsx
  src/constants/attendance.ts
  src/lib/types/index.ts
  src/pages/Attendance.tsx
  src/utils/splitTimestamp.ts
Labels: 새로운 기능, 완료

#76 ✨ Feat: 헤더, 사이드바 ui 추가 및 api 연결
  src/components/Alert.tsx
  src/components/Buttons/AnnualBtn.tsx
  src/components/Buttons/ApplyBtn.tsx
  src/components/Buttons/Btn.tsx
  src/components/Buttons/DutyBtn.tsx
  src/components/Buttons/ModalBtn.tsx
  src/components/Buttons/RejectBtn.tsx
  src/components/Buttons/StyledButton.tsx
  src/components/Buttons/getButton.ts
  src/components/Header/MainHeader.tsx
  src/components/Header/WorkTimer.tsx
  src/components/Modals/RequestModal.tsx
  src/components/SideBar.tsx
  src/constants/buttons.ts
  src/constants/modals.ts
  src/constants/password.ts
  src/constants/userInfo.ts
  src/hooks/useModal.ts
  src/lib/api/index.ts
  src/lib/types/index.ts
  src/pages/Layout.tsx
  src/pages/Login.tsx
  src/pages/Password.tsx
  src/pages/SignUp.tsx
  src/pages/UserInfo.tsx
  src/styles/Themes.ts
Labels: 새로운 기능, 완료

#84 🐛 Fix: 빌드 에러 해결
  src/components/Buttons/StyledButton.tsx
  src/lib/types/index.ts
  src/states/stateUserdata.ts
Labels: 버그, 완료

#86 🌷 Release: v2.0.0
  .gitignore
  package-lock.json
  package.json
  public/backgroundlogo 2.png
  src/components/Alert.tsx
  src/components/Buttons/AnnualBtn.tsx
  src/components/Buttons/ApplyBtn.tsx
  src/components/Buttons/Btn.tsx
  src/components/Buttons/DutyBtn.tsx
  src/components/Buttons/ExelBtn.tsx
  src/components/Buttons/ModalBtn.tsx
  src/components/Buttons/RejectBtn.tsx
  src/components/Buttons/StyledButton.tsx
  src/components/Buttons/getButton.ts
  src/components/Calendar/CalendarBody.tsx
  src/components/Calendar/CalendarList.tsx
  src/components/DashBoard.tsx
  src/components/Header/MainHeader.tsx
  src/components/Header/WorkTimer.tsx
  src/components/Modals/CalAnnualModal.tsx
  src/components/Modals/CalDutyModal.tsx
  src/components/Modals/RequestModal.tsx
  src/components/Modals/checkModal.tsx
  src/components/SideBar.tsx
  src/components/Table/GridTable.tsx
  src/constants/attendance.ts
  src/constants/buttons.ts
  src/constants/calendar.ts
  src/constants/dashBoard.ts
  src/constants/login.ts
  src/constants/modals.ts
  src/constants/password.ts
  src/constants/requestList.ts
  src/constants/sideBar.ts
  src/constants/signup.ts
  src/constants/userInfo.ts
  src/hooks/useModal.ts
  src/lib/api/index.ts
  src/lib/types/index.ts
  src/pages/Attendance.tsx
  src/pages/Calendar.tsx
  src/pages/Layout.tsx
  src/pages/Login.tsx
  src/pages/Password.tsx
  src/pages/RequestList.tsx
  src/pages/SignUp.tsx
  src/pages/UserInfo.tsx
  src/pages/index.tsx
  src/states/stateAlert.ts
  src/states/stateModal.ts
  src/states/stateUserdata.ts
  src/styles/Themes.ts
  src/utils/convertDay.ts
  src/utils/convertTime.ts
  src/utils/decode.ts
  src/utils/getCategory.ts
  src/utils/getDataCategory.ts
  src/utils/getEvaluation.ts
  src/utils/getPhone.ts
  src/utils/splitTimestamp.ts
Labels: 배포

#90 🌷 Release: v2.0.0 배포
  src/lib/api/index.ts
Labels: 배포

#92 🔨 Refactor: 성능 최적화를 위한 리팩토링
  index.html
  package-lock.json
  package.json
  src/components/Alert.tsx
  src/components/Calendar/CalendarBody.tsx
  src/components/Calendar/CalendarList.tsx
  src/components/DashBoard.tsx
  src/components/Header/MainHeader.tsx
  src/components/Header/WorkTimer.tsx
  src/components/Modals/RequestModal.tsx
  src/components/SideBar.tsx
  src/lib/api/index.ts
  src/pages/Attendance.tsx
  src/pages/Layout.tsx
  src/pages/SignUp.tsx
  src/pages/index.tsx
Labels: 완료

#93 🌷 Build: lazy loading, Suspense 적용 버전 빌드 (v2.0.1)
  index.html
  src/components/Calendar/CalendarBody.tsx
  src/components/Calendar/CalendarList.tsx
  src/components/DashBoard.tsx
  src/components/Header/MainHeader.tsx
  src/components/Header/WorkTimer.tsx
  src/components/Modals/RequestModal.tsx
  src/components/SideBar.tsx
  src/pages/Attendance.tsx
  src/pages/Layout.tsx
  src/pages/SignUp.tsx
  src/pages/index.tsx
Labels: 배포
